name: Deploy to WordPress.org
on:
  release:
    types: [released]
  # Allow manual triggering of the workflow.
  workflow_dispatch:
jobs:
  release:
    name: New release to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install SVN (Subversion)
        run: |
          sudo apt-get update
          sudo apt-get install subversion

      - name: Build # Remove or modify this step as needed
        run: |
          npm install
          npm run build
      - name: Push to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # 2.3.0
        env:
          SLUG: liveblog
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
