name: Run PHPUnit

on:
  # Run on all pushes and on all pull requests.
  # Prevent the "push" build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    name: WP ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    env:
      WP_VERSION: ${{ matrix.wordpress }}

    strategy:
      matrix:
        wordpress: ["6.4", "latest"]
        php: ["7.4", "8.0"]
        include:
          - php: "8.0"
            extensions: pcov
            ini-values: pcov.directory=., "pcov.exclude=\"~(vendor|tests)~\""
            coverage: pcov
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install wordpress environment
        run: npm install -g @wordpress/env

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: ${{ matrix.ini-values }}
          coverage: ${{ matrix.coverage }}
          tools: composer

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1
        with:
          composer-options: "${{ matrix.composer-options }}"

      - name: Setup wp-env
        run: wp-env start
        env:
          WP_ENV_CORE: WordPress/WordPress#${{ matrix.wordpress == 'latest' && 'master' || matrix.wordpress }}

      - name: Run integration tests (single site)
        if: ${{ matrix.php != 8.0 }}
        run: composer test-integration
      - name: Run integration tests (single site with code coverage)
        if: ${{ matrix.php == 8.0 }}
        run: composer coverage-ci
      - name: Run integration tests (multisite)
        run: composer test-integration-ms
